config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'main#index'
  resources :players
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
# frozen_string_literal: true

class Player < ApplicationRecord
  attribute :player_picture, :string, default: ''

  has_one_attached :picture

  validates :name, presence: true
  validates :foot, presence: true, inclusion: { in: %w[Left Right Both] }
  validates :age, numericality: { only_integer: true }

  before_save :age

  def has_picture?
    File.exist?(ActiveStorage::Blob.service.path_for(picture.key))
  end

  def age
    ((Date.today - date_of_birth) / 365).floor if date_of_birth
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/players_controller.rb
# frozen_string_literal: true

class PlayersController < ApplicationController
  before_action :set_player, except: %w[new create index]

  def index
    @players = Player.order('name')
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    PictureAttachmentService.attach(@player, player_params[:player_picture])
    if @player.save
      redirect_to @player, notice: 'Successfuly created player.'
    else
      flash[:error] = @player.errors.full_messages
      render :new
    end
  end

  private

  def set_player
    @player = Player.find(params[:id])
  end

  def player_params
    params.require(:player).permit(:name, :age, :foot, :position, :current_club,
                                   :height, :date_of_birth, :place_of_birth, :player_picture)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def bootstrap_class_for(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/players_helper.rb
module PlayersHelper
  def heightilize(height)
    "#{height.to_i}cm"
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}
    %title WebcamRails
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'shared/notifications'
    = yield

app/views/main/index.html.haml
.container
  = image_tag 'road.jpg'
  = link_to 'Admin panel', players_path, class: 'btn'

app/views/players/_form.html.haml
= form_with(model: @player, local: true) do |form|
  .ml-4.mb-4
    .row
      .card
        - if @player.picture.attached? && @player.has_picture?
          = image_tag @player.picture, class: 'card-img-top', id: 'shot'
        - else
          = image_tag 'default.jpg', class: 'card-img-top', id: 'shot'
      .card.ml-2#viewfinder
        %video{width: '288', height: '301', autoplay: true}
      .form-group.col-6.mt-2
        %button.btn.btn-dark.btn-sm#changePicture{type: 'button'} Change Picture
        %button.btn.btn-dark.btn-sm#snap{type: 'button'} Snap
      .form-group.col-6
        = form.label :name
        = form.text_field :name, class: 'form-control'
      .form-group.col-6
        = form.label :date_of_birth
        = form.date_field :date_of_birth, class: 'form-control'
      .form-group.col-6
        = form.label :place_of_birth
        = form.text_field :place_of_birth, class: 'form-control'
      .form-group.col-6
        = form.label :height
        = form.text_field :height, class: 'form-control'
      .form-group.col-6
        = form.label :position
        = form.text_field :position, class: 'form-control'
      .form-group.col-6
        = form.label :foot
        = form.select :foot, ['Left', 'Right', 'Both'],{}, class: 'form-control'
      .form-group.col-6
        = form.label :current_club
        = form.text_field :current_club, class: 'form-control'
    .row
      .form-group.col-12.text-center
        = form.submit class: 'btn btn-dark'
        = link_to 'Back', :back, class: 'btn btn-dark ml-4'
    = form.hidden_field :player_picture, value: @player.player_picture

app/views/players/edit.html.haml
= render 'form'

app/views/players/index.html.haml
%table.table.table-hover.my-class
  %thead.thead-dark
    %tr
      %th Name
      %th Birthdate
      %th Age
      %th Height
      %th Citezenship
      %th Position
      %th Foot
      %th Club
      %th{ colspan: '3'}
  %tbody
    - @players.each do |player|
      %tr
        %td= player.name
        %td= player.date_of_birth
        %td= player.age
        %td= heightilize(player.height)
        %td= player.place_of_birth
        %td= player.position
        %td= player.foot
        %td= player.current_club
        %td= link_to 'Show', player_path(player)
        %td= link_to 'Edit', edit_player_path(player)
        %td= link_to 'Delete', player_path(player), method: :delete

app/views/players/new.html.haml
= render 'form'

app/views/players/show.html.haml
.d-flex.justify-content-center
  .card
    - if @player.picture.attached? && @player.has_picture?
      = image_tag @player.picture, class: 'card-img-top'
    - else
      = image_tag 'default.jpg', class: 'card-img-top'

    .card-body
      %h5.card-title= @player.name
    %ul.list-group.list-group-flush
      %li.list-group-item= "Birthday: #{@player.date_of_birth}"
      %li.list-group-item= "Age: #{@player.age}"
      %li.list-group-item= "Height: #{heightilize(@player.height)}"
      %li.list-group-item= "Position: #{@player.position}"
      %li.list-group-item= "Foot: #{@player.foot}"
      %li.list-group-item= "Club: #{@player.current_club}"
    .card-body
      = link_to "Edit", edit_player_path(@player), class: 'card-link btn btn-dark'
      = link_to "Back", :back, class: 'card-link btn btn-dark'

app/views/shared/_flash_msg.html.haml
%div.myAlert{class: "alert #{bootstrap_class_for(type)} alert-dismissible fade show", role: "alert"}
  %button.close{"data-aria-label": "Close", "data-dismiss": "alert", type: "button"}
    %span{"aria-hidden": "true"} ×
  .text
    = content

app/views/shared/_notifications.html.haml
- flash.each do |type, content|
  - if content.respond_to?('each')
    - content.each do |item|
      = render 'shared/flash_msg', type: type, content: item
  - else
    = render 'shared/flash_msg', type: type, content: content